@extends('dashboard.layout')
@section('title','Dashboard — DevPortfolio')
@section('dashboard-content')
<div class="mx-auto max-w-5xl"><div class="mb-8"><h1 class="text-2xl font-semibold tracking-tight text-white">Selamat Datang, {{ $user->display_name }}!</h1><p class="mt-1 text-sm text-[#6b7280]">Kelola portfolio dan profil Anda dari sini.</p></div>
<div class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-3">@foreach([['Total Portfolio',$portfolioCount,'folder','from-cyan-500 to-blue-600'],['Profile Lengkap',$user->profile?'Ya':'Belum','user','from-purple-500 to-pink-600'],['Skill',$skillCount,'dashboard','from-amber-500 to-orange-600']] as [$l,$v,$i,$g])<div class="rounded-2xl border border-[#1f1f2e] bg-[#111118] p-5"><div class="mb-3 grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br {{ $g }} text-white"><x-icon :name="$i" class="h-5 w-5"/></div><div class="text-2xl font-semibold text-white">{{ $v }}</div><div class="text-sm text-[#6b7280]">{{ $l }}</div></div>@endforeach</div>
<div class="mb-8 grid grid-cols-1 gap-4 md:grid-cols-2"><a href="{{ route('dashboard.portfolio') }}" class="group rounded-2xl border border-[#1f1f2e] bg-[#111118] p-6 hover:border-cyan-500/30"><div class="mb-4 flex items-start justify-between"><div class="grid h-12 w-12 place-items-center rounded-xl border border-cyan-500/20 bg-cyan-500/10"><x-icon name="folder" class="h-6 w-6 text-cyan-400"/></div><x-icon name="arrow-right" class="h-5 w-5 text-[#4b5563] transition group-hover:translate-x-1 group-hover:text-cyan-400"/></div><h3 class="font-medium text-white">Upload Portfolio</h3><p class="mt-1 text-sm text-[#6b7280]">Tambahkan screenshot atau video project Anda beserta deskripsinya.</p></a>
<a href="{{ route('dashboard.profile') }}" class="group rounded-2xl border border-[#1f1f2e] bg-[#111118] p-6 hover:border-purple-500/30"><div class="mb-4 flex items-start justify-between"><div class="grid h-12 w-12 place-items-center rounded-xl border border-purple-500/20 bg-purple-500/10"><x-icon name="user" class="h-6 w-6 text-purple-400"/></div><x-icon name="arrow-right" class="h-5 w-5 text-[#4b5563] transition group-hover:translate-x-1 group-hover:text-purple-400"/></div><h3 class="font-medium text-white">Data Profile & CV</h3><p class="mt-1 text-sm text-[#6b7280]">Isi informasi pribadi, pendidikan, pengalaman kerja, dan skill Anda.</p></a></div>
<div class="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-cyan-500/20 bg-gradient-to-r from-cyan-500/10 to-blue-600/10 p-6"><div><h3 class="font-medium text-white">Portfolio Publik Anda</h3><p class="mt-1 text-sm text-[#6b7280]">Bagikan link ini kepada calon employer atau klien.</p><div class="mt-1 font-mono text-sm text-cyan-400">{{ route('portfolio.public',$user->username) }}</div></div><div class="flex gap-2"><button type="button" data-copy="{{ route('portfolio.public',$user->username) }}" class="flex items-center gap-2 rounded-xl border border-[#2a2a3e] bg-[#111118] px-4 py-2 text-sm text-[#9ca3af]"><x-icon name="copy" class="h-4 w-4"/> Copy</button><a href="{{ route('portfolio.public',$user->username) }}" target="_blank" class="flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-medium text-white"><x-icon name="external-link" class="h-4 w-4"/> Lihat Sekarang</a></div></div>
</div>
@endsection
