@extends('layouts.app')
@section('title',($user->profile?->name?:$user->username).' — Portfolio')
@section('content')
@php($profile=$user->profile)
<div class="min-h-screen bg-[#0a0a0f]"><div class="relative overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-cyan-500/10 via-transparent to-blue-600/10"></div><div class="relative mx-auto max-w-5xl px-6 pb-12 pt-16 sm:pt-20">
<div class="flex flex-col items-center gap-6 sm:flex-row sm:items-start"><div class="h-24 w-24 shrink-0 rounded-2xl bg-gradient-to-br from-cyan-500 to-blue-600 p-0.5"><div class="h-full w-full overflow-hidden rounded-[14px] bg-[#111118]">@if($profile?->avatar_url)<img src="{{ $profile->avatar_url }}" class="h-full w-full object-cover" alt="{{ $profile->name }}">@else<div class="flex h-full w-full items-center justify-center text-3xl text-white">{{ strtoupper(substr($profile?->name?:$user->username,0,1)) }}</div>@endif</div></div>
<div class="text-center sm:text-left"><h1 class="text-3xl font-semibold tracking-tight text-white">{{ $profile?->name?:$user->username }}</h1><p class="mt-1 text-sm text-cyan-400">@{{ $user->username }}</p>@if($profile?->bio)<p class="mt-3 max-w-xl text-sm leading-6 text-[#9ca3af]">{{ $profile->bio }}</p>@endif
<div class="mt-3 flex flex-wrap items-center justify-center gap-4 text-sm text-[#6b7280] sm:justify-start">@if($profile?->address)<span class="flex items-center gap-1.5"><x-icon name="map-pin" class="h-4 w-4 text-cyan-500/60"/>{{ $profile->address }}</span>@endif @if($profile?->phone)<span class="flex items-center gap-1.5"><x-icon name="phone" class="h-4 w-4 text-cyan-500/60"/>{{ $profile->phone }}</span>@endif<span class="flex items-center gap-1.5"><x-icon name="mail" class="h-4 w-4 text-cyan-500/60"/>{{ $user->email }}</span></div>
@if($profile?->socialLinks?->count())<div class="mt-4 flex flex-wrap justify-center gap-2 sm:justify-start">@foreach($profile->socialLinks as $s)<a href="{{ $s->url }}" target="_blank" rel="noopener" class="flex items-center gap-1.5 rounded-xl border border-[#1f1f2e] bg-[#111118] px-3 py-1.5 text-sm text-[#9ca3af] hover:border-cyan-500/30 hover:text-white">{{ $s->platform }}</a>@endforeach</div>@endif</div></div>
@if($profile?->skills?->count())<div class="mt-8 flex flex-wrap gap-2">@foreach($profile->skills as $s)<span class="flex items-center gap-1.5 rounded-full border border-[#1f1f2e] bg-[#111118] px-2.5 py-1 text-xs text-[#9ca3af]"><span class="h-1.5 w-1.5 rounded-full bg-cyan-400"></span>{{ $s->name }}</span>@endforeach</div>@endif
</div></div>
<div class="sticky top-0 z-20 border-b border-[#1f1f2e] bg-[#0a0a0f]/80 backdrop-blur-md"><div class="mx-auto flex max-w-5xl gap-1 px-6 py-2"><a href="{{ route('portfolio.public',$user->username,['q'=>$query]) }}" class="rounded-lg px-4 py-2 text-sm {{ request('section','portfolio')!=='about'?'bg-cyan-500/10 text-cyan-400':'text-[#6b7280] hover:text-white' }}">Portfolio ({{ $user->portfolios()->count() }})</a><a href="{{ route('portfolio.public',$user->username,['section'=>'about']) }}" class="rounded-lg px-4 py-2 text-sm {{ request('section')==='about'?'bg-cyan-500/10 text-cyan-400':'text-[#6b7280] hover:text-white' }}">Tentang Saya</a></div></div>
<div class="mx-auto max-w-5xl px-6 py-10">
@if(request('section')==='about')
<div class="space-y-8">@if(!$profile)<div class="py-20 text-center text-[#4b5563]">Belum ada data profil yang tersedia.</div>@else
<section class="card p-6"><div class="mb-5 flex items-center gap-3"><x-icon name="user" class="h-5 w-5 text-cyan-400"/><h2 class="font-medium text-white">Informasi Pribadi</h2></div><div class="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2">@if($profile->birth_date)<div><p class="text-xs text-[#4b5563]">Tanggal Lahir</p><p class="mt-1 text-[#9ca3af]">{{ $profile->birth_date->translatedFormat('d F Y') }}</p></div>@endif @if($profile->address)<div><p class="text-xs text-[#4b5563]">Lokasi</p><p class="mt-1 text-[#9ca3af]">{{ $profile->address }}</p></div>@endif @if($profile->phone)<div><p class="text-xs text-[#4b5563]">Telepon</p><p class="mt-1 text-[#9ca3af]">{{ $profile->phone }}</p></div>@endif @if(count($profile->hobbies??[]))<div><p class="text-xs text-[#4b5563]">Hobi</p><p class="mt-1 text-[#9ca3af]">{{ implode(', ',$profile->hobbies) }}</p></div>@endif</div></section>
@if($profile->skills->count())<section class="card p-6"><h2 class="mb-5 font-medium text-white">Skill & Keahlian</h2>@foreach($profile->skills->groupBy('category') as $cat=>$skills)<div class="mb-5 last:mb-0"><h3 class="mb-3 text-xs uppercase tracking-wider text-[#6b7280]">{{ $cat }}</h3><div class="space-y-3">@foreach($skills as $s)<div><div class="mb-1 flex justify-between text-sm"><span class="text-[#9ca3af]">{{ $s->name }}</span><span class="text-cyan-400">{{ $s->level }}%</span></div><div class="h-1.5 overflow-hidden rounded-full bg-[#1a1a27]"><div class="h-full rounded-full bg-gradient-to-r from-cyan-500 to-blue-600" style="width:{{ $s->level }}%"></div></div></div>@endforeach</div></div>@endforeach</section>@endif
@if($profile->education->count())<section class="card p-6"><h2 class="mb-5 font-medium text-white">Riwayat Pendidikan</h2><div class="space-y-5">@foreach($profile->education as $e)<div class="border-l border-[#2a2a3e] pl-4"><div class="flex flex-wrap justify-between gap-2"><div><h3 class="text-sm font-medium text-white">{{ trim(($e->degree?$e->degree.' — ':'').$e->field)?:'Pendidikan' }}</h3><p class="mt-1 text-xs text-cyan-400">{{ $e->institution }}</p></div><span class="text-xs text-[#4b5563]">{{ $e->start_year }}{{ $e->end_year?' – '.$e->end_year:' – Sekarang' }}</span></div>@if($e->description)<p class="mt-2 text-sm leading-6 text-[#6b7280]">{{ $e->description }}</p>@endif</div>@endforeach</div></section>@endif
@if($profile->experiences->count())<section class="card p-6"><h2 class="mb-5 font-medium text-white">Pengalaman Kerja</h2><div class="space-y-5">@foreach($profile->experiences as $e)<div class="border-l border-[#2a2a3e] pl-4"><div class="flex flex-wrap justify-between gap-2"><div><h3 class="text-sm font-medium text-white">{{ $e->position }}</h3><p class="mt-1 text-xs text-cyan-400">{{ $e->company }}</p></div><span class="text-xs text-[#4b5563]">{{ $e->start_date?->format('M Y') }} – {{ $e->current?'Sekarang':$e->end_date?->format('M Y') }}</span></div>@if($e->description)<p class="mt-2 text-sm leading-6 text-[#6b7280]">{{ $e->description }}</p>@endif</div>@endforeach</div></section>@endif
</div>@endif
@else
@if($allTags->count())<div class="mb-6 flex flex-wrap gap-2"><a href="{{ route('portfolio.public',$user->username,['q'=>$query]) }}" class="rounded-full border px-3 py-1.5 text-xs {{ $tag===''?'border-cyan-500/30 bg-cyan-500/20 text-cyan-400':'border-[#2a2a3e] text-[#6b7280]' }}">Semua</a>@foreach($allTags as $t)<a href="{{ route('portfolio.public',$user->username,['tag'=>$t,'q'=>$query]) }}" class="rounded-full border px-3 py-1.5 text-xs {{ $tag===$t?'border-cyan-500/30 bg-cyan-500/20 text-cyan-400':'border-[#2a2a3e] text-[#6b7280]' }}">{{ $t }}</a>@endforeach</div>@endif
<form class="relative mb-6 max-w-xl"><x-icon name="search" class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#4b5563]"/><input name="q" value="{{ $query }}" placeholder="Cari project..." class="field w-full pl-9">@if($tag)<input type="hidden" name="tag" value="{{ $tag }}">@endif</form>
@if($portfolios->count())<div class="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach($portfolios as $p)<article class="group cursor-pointer overflow-hidden rounded-2xl border border-[#1f1f2e] bg-[#111118]" data-portfolio-card data-title="{{ $p->title }}" data-type="{{ $p->type }}" data-media="{{ $p->media_url }}" data-description="{{ $p->description }}" data-tags="{{ implode('|',$p->tags??[]) }}" data-live="{{ $p->live_url }}" data-repo="{{ $p->repo_url }}"><div class="relative aspect-video overflow-hidden bg-[#1a1a27]">@if($p->type==='video')<video src="{{ $p->media_url }}" class="h-full w-full object-cover" muted></video>@else<img src="{{ $p->thumbnail_url }}" alt="{{ $p->title }}" class="h-full w-full object-cover transition group-hover:scale-105">@endif<div class="absolute inset-0 grid place-items-center bg-black/50 opacity-0 transition group-hover:opacity-100"><x-icon name="eye" class="h-8 w-8 text-white"/></div></div><div class="p-4"><h3 class="text-sm font-medium text-white">{{ $p->title }}</h3><p class="mt-1 line-clamp-2 text-xs leading-5 text-[#6b7280]">{{ $p->description }}</p><div class="mt-3 flex flex-wrap gap-1">@foreach(array_slice($p->tags??[],0,3) as $t)<span class="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-2 py-0.5 text-xs text-cyan-400">{{ $t }}</span>@endforeach</div></div></article>@endforeach</div>@else<div class="py-20 text-center text-[#4b5563]"><x-icon name="code" class="mx-auto mb-4 h-8 w-8"/><p>Belum ada portfolio yang ditampilkan.</p></div>@endif
@endif
</div></div>
<div id="portfolio-modal" class="fixed inset-0 z-[60] hidden items-center justify-center bg-black/80 p-4"><div class="w-full max-w-3xl overflow-hidden rounded-2xl border border-[#1f1f2e] bg-[#111118]"><div class="flex items-center justify-between border-b border-[#1f1f2e] px-6 py-4"><h2 id="modal-title" class="font-medium text-white"></h2><button type="button" data-close-modal class="text-[#4b5563]"><x-icon name="x" class="h-5 w-5"/></button></div><div id="modal-media" class="aspect-video bg-[#0a0a0f]"></div><div class="p-6"><p id="modal-description" class="mb-4 text-sm text-[#9ca3af]"></p><div id="modal-tags" class="mb-4 flex flex-wrap gap-2"></div><div class="flex gap-4 text-sm"><a id="modal-live" target="_blank" class="hidden items-center gap-2 text-cyan-400"><x-icon name="external-link" class="h-4 w-4"/> Live Demo</a><a id="modal-repo" target="_blank" class="hidden items-center gap-2 text-[#9ca3af]"><x-icon name="github" class="h-4 w-4"/> Source Code</a></div></div></div></div>
@endsection
