@extends('dashboard.layout')
@section('title','Portfolio — DevPortfolio')
@section('dashboard-content')
<div class="mx-auto max-w-6xl"><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-semibold text-white">Portfolio</h1><p class="mt-1 text-sm text-[#6b7280]">Kelola karya yang tampil pada halaman publik Anda.</p></div><a href="#upload" class="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-4 py-2.5 text-sm font-medium text-white"><x-icon name="upload" class="h-4 w-4"/> Upload Portfolio</a></div>
<form class="relative mb-6 max-w-xl"><x-icon name="search" class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#4b5563]"/><input name="q" value="{{ $search }}" placeholder="Cari judul atau tag..." class="field w-full pl-9"></form>
@if($errors->any())<div class="mb-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{{ $errors->first() }}</div>@endif
<div class="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">@forelse($portfolios as $p)<article class="group overflow-hidden rounded-2xl border border-[#1f1f2e] bg-[#111118]"><button type="button" class="portfolio-preview block w-full text-left" data-title="{{ $p->title }}" data-type="{{ $p->type }}" data-media="{{ $p->media_url }}" data-description="{{ $p->description }}" data-tags="{{ implode('|',$p->tags??[]) }}" data-live="{{ $p->live_url }}" data-repo="{{ $p->repo_url }}">
<div class="relative aspect-video overflow-hidden bg-[#1a1a27]">@if($p->type==='video')<video src="{{ $p->media_url }}" class="h-full w-full object-cover" muted preload="metadata"></video>@else<img src="{{ $p->thumbnail_url }}" alt="{{ $p->title }}" class="h-full w-full object-cover transition group-hover:scale-105">@endif<div class="absolute inset-0 grid place-items-center bg-black/50 opacity-0 transition group-hover:opacity-100"><x-icon name="eye" class="h-8 w-8 text-white"/></div></div><div class="p-4"><h3 class="text-sm font-medium text-white">{{ $p->title }}</h3><p class="mt-1 line-clamp-2 text-xs leading-5 text-[#6b7280]">{{ $p->description }}</p><div class="mt-3 flex flex-wrap gap-1">@foreach(array_slice($p->tags??[],0,3) as $t)<span class="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-2 py-0.5 text-xs text-cyan-400">{{ $t }}</span>@endforeach</div></div></button>
<div class="flex justify-end border-t border-[#1f1f2e] px-4 py-3"><form method="POST" action="{{ route('dashboard.portfolio.destroy',$p) }}" onsubmit="return confirm('Hapus portfolio ini?')">@csrf @method('DELETE')<button class="flex items-center gap-1.5 text-xs text-[#6b7280] hover:text-red-400"><x-icon name="trash" class="h-4 w-4"/> Hapus</button></form></div></article>@empty
<div class="md:col-span-2 lg:col-span-3 py-16 text-center text-[#4b5563]"><div class="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-2xl border border-[#1f1f2e] bg-[#111118]"><x-icon name="folder" class="h-6 w-6"/></div><p>Belum ada portfolio. Upload karya pertama Anda.</p></div>
@endforelse</div>
<section id="upload" class="mt-10 rounded-2xl border border-[#1f1f2e] bg-[#111118] p-6"><div class="mb-5"><h2 class="text-lg font-semibold text-white">Upload Portfolio Baru</h2><p class="mt-1 text-sm text-[#6b7280]">Gambar/video maksimal 50 MB.</p></div><form method="POST" action="{{ route('dashboard.portfolio.store') }}" enctype="multipart/form-data" class="grid grid-cols-1 gap-4 md:grid-cols-2">@csrf
<div class="md:col-span-2"><label class="label">Judul</label><input name="title" value="{{ old('title') }}" class="field w-full" required placeholder="E-Commerce Platform"></div><div class="md:col-span-2"><label class="label">Deskripsi</label><textarea name="description" class="field min-h-28 w-full" required></textarea></div><div><label class="label">Media</label><input name="media" type="file" required accept="image/*,video/*" class="file-field"></div><div><label class="label">Thumbnail (opsional)</label><input name="thumbnail" type="file" accept="image/*" class="file-field"></div><div><label class="label">Tags</label><input name="tags" value="{{ old('tags') }}" class="field w-full" placeholder="Laravel, TailwindCSS, MySQL"></div><div><label class="label">Live URL</label><input name="live_url" value="{{ old('live_url') }}" type="url" class="field w-full"></div><div><label class="label">Repository URL</label><input name="repo_url" value="{{ old('repo_url') }}" type="url" class="field w-full"></div><div class="md:col-span-2"><button class="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-2.5 text-sm font-medium text-white"><x-icon name="upload" class="h-4 w-4"/> Simpan Portfolio</button></div></form></section></div>
<div id="portfolio-modal" class="fixed inset-0 z-[60] hidden items-center justify-center bg-black/80 p-4"><div class="w-full max-w-3xl overflow-hidden rounded-2xl border border-[#1f1f2e] bg-[#111118]"><div class="flex items-center justify-between border-b border-[#1f1f2e] px-6 py-4"><h2 id="modal-title" class="font-medium text-white"></h2><button type="button" data-close-modal class="text-[#4b5563]"><x-icon name="x" class="h-5 w-5"/></button></div><div id="modal-media" class="aspect-video bg-[#0a0a0f]"></div><div class="p-6"><p id="modal-description" class="mb-4 text-sm text-[#9ca3af]"></p><div id="modal-tags" class="mb-4 flex flex-wrap gap-2"></div><div class="flex gap-4 text-sm"><a id="modal-live" target="_blank" class="hidden items-center gap-2 text-cyan-400"><x-icon name="external-link" class="h-4 w-4"/> Live Demo</a><a id="modal-repo" target="_blank" class="hidden items-center gap-2 text-[#9ca3af]"><x-icon name="github" class="h-4 w-4"/> Source Code</a></div></div></div></div>
@endsection
